### ISSUE TITLE
Flips on last axis?

### ISSUE THREAD

**Issue by embeh** [AutodeskRoboticsLab/Mimic#6]
Just found this project and it looks very promising.
While watching the intro video at https://youtu.be/bc3SqEXcE5Q I noticed some rather violent flips of the last rotation axis (the 'wrist') about 20 seconds into the video. This is something you probably would not want to see on real hardware - what's the status on these things? Is the plugin going to include some filters to limit speed/acceleration on specific axes?
Thanks!

**Comment by evanatherton** [comment]
Hey there!

Yes, that axis is definitely flipping around in that video. That was a quick animation that was done just to show the concept. One of the key benefits of Mimic is that you can see things like that visually while you're animating so that you can then change your animation strategy to avoid them.

We check velocity, acceleration, and jerk before exporting, which catches things like that if you miss it visually for some reason. We don't, however, modify the robot program to limit these things because that would change the trajectory of the intended animation. What we try to do is give as much visual information to the animator so that they can animate within the dynamic limits of the physical robot.
